CC = gcc
CFLAGS = -Wall -Wextra -Werror -Wpedantic -std=c99

SRC_AES = aes.c 
SRC_STSIO = stsio.c
SRC_SHA256 = sha256.c
TARGET_AES = aes
TARGET_STSIO = stsio
TARGET_SHA256 = sha256

all:  $(TARGET_AES) $(TARGET_STSIO) $(TARGET_SHA256)

$(TARGET_AES): $(SRC_AES)
	$(CC) $(CFLAGS) -o $(TARGET_AES) $(SRC_AES)

$(TARGET_STSIO): $(SRC_STSIO)
	$(CC) $(CFLAGS) -o $(TARGET_STSIO) $(SRC_STSIO)

$(TARGET_SHA256): $(SRC_SHA256)
	$(CC) $(CFLAGS) -o $(TARGET_SHA256) $(SRC_SHA256)


clean:
	rm -f $(TARGET_AES) $(TARGET_STSIO) $(TARGET_SHA256)